### ISSUE TITLE
This image is not rotated

### ISSUE THREAD

**Issue by CharlesWu123** [phamquiluan/jdeskew#15]
![image](https://user-images.githubusercontent.com/38948322/191926152-cbd23a3a-6885-4788-9f8a-a1c2041222dd.png)

**Comment by phamquiluan** [comment]
@CharlesWu123 Check this notebook, I will show you how it done
https://colab.research.google.com/drive/1KjLOIW68hj4FL5Y4wcqkBrxkIldPXkUo?usp=sharing

**Comment by CharlesWu123** [comment]
thanks，this is a screenshot，which can be handled correctly. But the original image not.  why?
![林杰-2 1 12-农业银行-6228480329446323571_27_00](https://user-images.githubusercontent.com/38948322/191932452-6dbd7b43-38be-4e0a-8571-56fab090b027.png)

**Comment by phamquiluan** [comment]
@CharlesWu123 recheck this, I'll show you how to inspect the Fourier magnitude via heatmap

https://colab.research.google.com/drive/1KjLOIW68hj4FL5Y4wcqkBrxkIldPXkUo?usp=sharing

**Reason:** In your image, besides the skew table, there are some straight components such as frame, title, and bar code. Hmm these components confuse the method.

**Solution 1:** Detach the table region out of your input first
**Solution 2:** Remove the frame then do the deskew again
**Solution 3:** Ensemble, split the images and deskew on smaller proportion, then aggregate the results (e.g. pick median value). 

What do you think? @CharlesWu123

**Comment by CharlesWu123** [comment]
very thanks, i think what you said is ok,  i will try it.

**Comment by temiwale88** [comment]
For posterity, solution 1 works. Remove / detect the table then use @phamquiluan jdeskew package.
