### ISSUE TITLE
Download Paper pre-print persion link in the readme.md is broken

### ISSUE THREAD

**Issue by ian-hank** [phamquiluan/jdeskew#16]
In the readme.md under section _Download Paper_, the link to the pre-print version does not work. It appears the GitHub page no longer exists at all (or is public) and leads to nowhere.

**Comment by phamquiluan** [comment]
@ian-hank it's here, https://ieeexplore.ieee.org/document/9897910

the pdf is free

**Comment by phamquiluan** [comment]
Thank you @ian-hank for reporting the issues. I updated the README.md :bow:
