### ISSUE TITLE
 How can I get the code for the other methods ?

### ISSUE THREAD

**Issue by shallweiwei** [phamquiluan/jdeskew#20]
Hi, I am a beginner in this field.Could you tell me how can I get the code for the other methods in the paper?

**Comment by phamquiluan** [comment]
@shallweiwei 
PypiDeskew: https://github.com/sbrunner/deskew
CMC-MSU:https://github.com/OLEGator30/DISEC-13
FredsDeskew:http://www.fmwconcepts.com/imagemagick/textdeskew/

For others, you'll need to contact the authors.

**Comment by shallweiwei** [comment]
Thank you very much for your help

**Comment by shallweiwei** [comment]
Hello, I am also very interested in the second best LRDE-EPITA method in the paper, and I noticed that it is also the champion of the competition, but I did not find its paper and specific code, may I ask whether you contacted the author by email or tried to reproduce this part by yourself?Thank you very much for your help
∧＿∧

**Comment by phamquiluan** [comment]
Hi @shallweiwei 
This is the paper: https://ieeexplore.ieee.org/document/7025523
You can find him here: https://www.lrde.epita.fr/~jonathan/contact.html

I emailed him to obtain the code, he is one of the kindest persons I ever met.

**Comment by shallweiwei** [comment]
Thanks a million!
I'll try to email him.Thank you again!
