### ISSUE TITLE
Dealing with angles > 90

### ISSUE THREAD

**Issue by parad0x96** [phamquiluan/jdeskew#21]
It seems to fail with angles > 90

**Comment by phamquiluan** [comment]
Could you give me an example? @parad0x96

**Comment by parad0x96** [comment]
Hey @phamquiluan  for example, I have an image which is upside down (180 degrees), it seems to output 0 as the angle

**Comment by phamquiluan** [comment]
That is not a skew problem. That is a rotation problem. @parad0x96
