### ISSUE TITLE
Using INTER_LINEAR instead of INTER_NEAREST

### ISSUE THREAD

**Issue by aymen20002005** [phamquiluan/jdeskew#23]
Hello,

In the rotate function in utility.py, I recommend using INTER_LINEAR instead of INTER_NEAREST, as linear interpolation provides better image quality. Although the nearest neighbor method is faster, preserving image quality is essential for this deskewing library, especially since it is intended for documents that will undergo OCR processing.

output_image = cv2.warpAffine(
        src=image,
        M=M,
        dsize=(w, h),
        flags=cv2.INTER_NEAREST,
        borderMode=border_mode,
        borderValue=None if border_mode == cv2.BORDER_REPLICATE else border_value,
    )

**Comment by phamquiluan** [comment]
@aymen20002005 Thank you so much for your feedback!

I would greatly appreciate if you could make a Pull Request to move the flag **flags=cv2.INTER_NEAREST,** to the parameter of the **rotate** function. The default value could be what you suggested. 

Thank you so much <3

**Comment by aymen20002005** [comment]
Thank you, @phamquiluan!
I have submitted the pull request.

**Comment by phamquiluan** [comment]
Thank you for the PR @aymen20002005, I have a comment, please have a check https://github.com/phamquiluan/jdeskew/pull/24#discussion_r1838981259
